### ISSUE TITLE
startXMLSynchro fails

### ISSUE THREAD

**Issue by r0bn** [r0bn/swp2#88]
Message appears instantly if you open a story in the console.

The function startXMlSynchro try's to split something that is not splitable
during parsing the xml from the server

Error Message:
```
TypeError: Cannot read property 'split' of undefined
    at Element.<anonymous> (http://storytellar.de/build/main.js:3277:73)
    at Function.n.extend.each (http://storytellar.de/build/vendor.js:38353:2882)
    at n.fn.n.each (http://storytellar.de/build/vendor.js:38353:847)
    at Element.<anonymous> (http://storytellar.de/build/main.js:3264:36)
    at Function.n.extend.each (http://storytellar.de/build/vendor.js:38353:2882)
    at n.fn.n.each (http://storytellar.de/build/vendor.js:38353:847)
    at Element.<anonymous> (http://storytellar.de/build/main.js:3258:30)
    at Function.n.extend.each (http://storytellar.de/build/vendor.js:38353:2882)
    at n.fn.n.each (http://storytellar.de/build/vendor.js:38353:847)
    at startXMLSynchro (http://storytellar.de/build/main.js:3199:24)
```

**Comment by Teammm** [comment]
In which STory-ID you had this error?

http://localhost:4001/#/story/XXX ?
